### ISSUE TITLE
Problem while importing data since 2023.3.0

### ISSUE THREAD

**Issue by alexz707** [DarkC35/ha_linznetz#12]
## Version of the custom_component
Latest from HACS

## Configuration

```yaml

Logger: homeassistant.components.automation.import_linz_netz_email_reports
Source: custom_components/linznetz/sensor.py:187
Integration: Automatisierung ([documentation](https://www.home-assistant.io/integrations/automation), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+automation%22))
First occurred: 6. März 2023 um 12:20:30 (2 occurrences)
Last logged: 6. März 2023 um 12:20:30

    Import Linz Netz Email Reports: Error executing script. Unexpected error for call_service at pos 1: '<' not supported between instances of 'float' and 'datetime.datetime'
    While executing automation automation.import_linz_netz_email_reports

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 795, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/linznetz/sensor.py", line 187, in import_report
    and last_inserted_stat[self.entity_id][0]["start"]
TypeError: '<' not supported between instances of 'float' and 'datetime.datetime'

```

## Describe the bug
With updating to latest home assistent version the import gets broken.
Currently there is only that error in the logs.
import stopped working after upgrading homeassistent.
Could you find out if you have the same problem?

**Comment by DarkC35** [comment]
Thanks for the info. Yeah it seems that they changed one of the internal APIs again (without mention it in the release notes), see these two PRs with the change and the fix (I'm using the tibber component as a reference again):
https://github.com/home-assistant/core/pull/87845
https://github.com/home-assistant/core/pull/88025

Not sure how to handle this one yet as I have to evaluate if the change could be made backwards compatible.

**Comment by alexz707** [comment]
thanks for the info.
yeah I thought an update is safe to do but they proved me wrong again.
I had a look at the fix of tibber - I guess you would convert the datetime obj to an timestamp including the timezone so not as in the fix from utc or did I understand that wrong?
you could add a contraint so the new version of your module just needs the march release?

**Comment by winterer** [comment]
I've got the same error after updating to Home Assistant 2023.3.3 / Supervisor 2023.03.1.
The changes in #13 seem to fix the problem. At least I could import the data again without error.

**Comment by alexz707** [comment]
Tried the fix and it's working fine! Huge thanks for that so I can see my power usage again :)
