### ISSUE TITLE
Fix break on daylight saving changes

### ISSUE THREAD

**Issue by DarkC35** [DarkC35/ha_linznetz#4]
Currently the integration breaks when it tries to import a report that does not multiple of 96 entries. This should be changed to allow more flexible time ranges in reports. This change should also consider daylight saving changes were reports do have 92/100 entries.

The current workarounds for this are:
1. only import reports with 96 entries
2. during daylight saving changes add up all overlapping values / add missing entires with "0" kwh (unfortunately this will "break" the energy dashboard for this day a bit) and import this "fixed" report again

**Comment by alexz707** [comment]
Thanks for writing this report, that's the reason why there were more than 96 entries on exactly one day :D

**Comment by DarkC35** [comment]
No this is actually expected behaviour because before the change it's UTC+2 and after the change UTC+1 (I guess), therefore they need to calculate and display this hour somehow and you want to know what you consume between 2:00-2:00 and 2:00-3:00. This integration currently uses only one Timezone setting because I needed this case to happen once to figure out how to react to the data. HA even shows a second 2:00 bar in the energy dashboard that is skipped when you use this workaround. 

Hopefully I will be able to fix this until the next change x'D Maybe everyone who uses this integration currently (and did not interact here in this issue) should subscribe to this issue to get notified when an update is ready.

**Comment by brandstaetter** [comment]
Also ran into this when trying to import my bulk export - please note this in the readme where the bulk import is mentioned. Easy "fix" would be to manually remove the 4 additional lines from the file.

huge thank you for creating this, was about to do something similar myself 👍

**Comment by DarkC35** [comment]
Thanks for pointing this out! I'm going to add this to the readme. Wasn't expecting that people who find this integration already turned QH values on beforehand and thought I would be save until the next change x'D 
The "cleaner" workaround is to add the duplicated lines to the existing ones since you don't lose some data in the overall calculation (would be about 0.5kWh).

Btw I'm glad that at least two other people are using this integration and hope it is helpful in your workflow.

If you two are interested I was thinking to write-up an issue/HA community post about the future for Austrian energy data analysis as there is an addon for all SmartMeters currently developed by the company Ginzinger commissioned by the "E-Wirtschaft Österreich" which could combine all the different integrations to one universal one (if those addons are kinda cheap as there is no pricing communicated yet).

**Comment by alexz707** [comment]
I have sent them an email in Novemeber according the adapter which is currently developed.
They told me they are currently sourcing the components and 1 year ago the estimated price per device was around 25 -30 €. They are not sure if they can hold that price but more or less that should be the expected price range. ;-)

Would be great if there will be an addon for HA so we can get the live power consumption :)

**Comment by brandstaetter** [comment]
Latest news I got was that they had troubles and delays sourcing the components. I'm also waiting for it to become available and am sure that we will be able to interface it with HA easily.

**Comment by DarkC35** [comment]
Thanks for your input, I'm glad that there is progress and that it's hopefully cheaper than expected! (Some IR based devices that cannot be used with the Linz Netz meters are available for about 80€ so I was afraid that this adapter would be in a similar price range.)

I just added the hint in the readme for this issue. I'm still not sure when I will actually get to fix/improve the calculation... Hopefully before the next change xD.

**Comment by DarkC35** [comment]
I just pushed a PR #11 that could fix this issue and maybe improve the logic. It would be nice if somebody could take a quick look on the modifications :) I only tested it with unit tests yet, maybe have to run some manual tests in a dev environment too.

**Comment by alexz707** [comment]
hi! just rebuilt my ha setup from scratch so I had to import the lin netz data again.
No errors and everything looks fine. Thanks a lot :)

BTW: Do you know a way how I can "import" the solar energy data without importing the ha DB?

**Comment by DarkC35** [comment]
Sorry I don't have any solar integrations running on my end (yet) so I'm not sure what you mean with importing solar energy data ^^'

Do you get them with LINZ NETZ or some other integration for your inverter? My best bet would be to open your old DB (with some tool like a sqlite viewer if you use sqlite or a viewer/management tool for your specific DB) and export your solar values in some file (sql, csv, ...) and try to import them in your new DB (would require some SQL tinkering). There is also an official SQL integraion in HA core but I don't know what it's capable of. 

Oh and of course document your whole process for your next clean install ;D
