### ISSUE TITLE
Parameter missing in new home assistant version.

### ISSUE THREAD

**Issue by alexz707** [DarkC35/ha_linznetz#5]
https://github.com/DarkC35/ha_linznetz/blob/2c35ee5a2b522c26b6c59fd5be2139f4bf991f0d/custom_components/linznetz/sensor.py#L127

if you add , {} to the call it works again ;)

**Comment by DarkC35** [comment]
Tanks for the info! I was afraid that something like rhis would happen after reading the release changelog x'D
I will try to fix this on the weekend and hopefully get some tests ready for the CI to catch failures until the next time something in the internal APIs changes.

**Comment by alexz707** [comment]
Maybe there are some more problems:
File "/config/custom_components/linznetz/sensor.py", line 142, in import_report
and dt_util.parse_datetime(

-> I think they changed the return value of last_inserted_stat[self.entity_id][0]["start"] from string to datetime?

**Comment by alexz707** [comment]
One more problem:

File "/config/custom_components/linznetz/sensor.py", line 149, in import_report
_sum = Decimal(last_inserted_stat[self.entity_id][0]["sum"])
2022-12-08 20:03:24.252 ERROR (MainThread) [homeassistant.components.automation.import_linz_netz_email_reports] Import Linz Netz Email Reports: Error executing script. Unexpected error for call_service at pos 1: 'sum'

sum is not defined anymore... 

I dumped the variable one line above the error:
 Result: {'start': datetime.datetime(2022, 12, 4, 22, 0, tzinfo=datetime.timezone.utc), 'end': datetime.datetime(2022, 12, 4, 23, 0, tzinfo=datetime.timezone.utc)}

I don't have a plan right now to fix that, maybe you have an idea ;)

**Comment by DarkC35** [comment]
Yeah I did not update my HA to 2022.12 yet because I was afraid that the integration breaks. I hope I get to fix it on the weekend... it already bugs me to think how such internal breaking changes need to be handled to ensure backward compatibility ^^'

**Comment by DarkC35** [comment]
Looking on the PR that changes the API the only core integration that rely on it is tibber and in the `tibber/sensor.py` file they had to add a `{"sum"}` argument.
https://github.com/home-assistant/core/commit/607a0e7697a640e524405f5560868125781bdf0c

**Comment by alexz707** [comment]
That's true with sum as param it works again ;)

**Comment by DarkC35** [comment]
I added a PR (#8) with an updated version of the `sensor.py` file that worked with the documented tests in a dev container. You could tests this code on your installation and give feedback if you are brave enough ;D 

I'm not sure when I will update my HA installation to > 2022.12.0 so I will wait with the merge a bit longer and maybe test a bit more.

**Comment by alexz707** [comment]
Just a quick feedback, everything is working as expected ;-)
Thanks a lot!
